name: Go Test
on:
  pull_request:
    paths: ['go/**/*.go']
jobs:
  go-test:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6.1
        with:
          go-version: '1.25'
      - run: go test go/excellent/*.go
