name: Test isEven
on:
  pull_request:
    paths: ['src/**/*.ts']
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # ワークフロー、ブランチでグルーピング
  cancel-in-progress: true
jobs:
  test-isEven:
    runs-on: ubuntu-slim
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      
      - run: bun test

