name: Test isEven
on:
  pull_request:
    paths: ['src/**/*.ts']
jobs:
  test-isEven:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2
      
      - run: bun test